from PySide6 import QtGui as QtGui
from PySide6.QtWidgets import QComboBox, QMainWindow, QSpinBox, QWidget
from pathlib import Path
from typing import Any, Sequence, Tuple
from window import Ui_MainWindow

def replace_underscores(text: str) -> str: ...

class SpinBox(QSpinBox, QWidget):
    def wheelEvent(self, event: QtGui.QWheelEvent): ...

class ComboBox(QComboBox, QWidget):
    def wheelEvent(self, event: QtGui.QWheelEvent): ...

class Window(QMainWindow, Ui_MainWindow):
    root_path: Path
    pkm_path: Path
    pkm_parse: dict[str, dict[str, dict[str, Any]]]
    pkm: dict[str, dict[str, Any]]
    move_items: Sequence[str]
    def __init__(self) -> None: ...
    def connect_slots(self) -> None: ...
    def name_changed(self) -> None: ...
    def add_move_item(self, level: int = ..., move: Union[str, None] = ...): ...
    def remove_move_item(self) -> None: ...
    def save_poke(self) -> None: ...
    def get_file_path(self, file_name: str) -> Tuple[Path, Path]: ...
