from PySide6.QtUiTools import QUiLoader as QUiLoader
from PySide6.QtWidgets import QMainWindow
from pathlib import Path
from typing import Any, Tuple
from window import Ui_MainWindow

class Window(QMainWindow, Ui_MainWindow):
    root_path: Path
    moves_path: Path
    moves_parse: dict[str, dict[str, dict[str, Any]]]
    moves: dict[str, dict[str, Any]]
    def __init__(self) -> None: ...
    def connect_slots(self) -> None: ...
    def name_changed(self) -> None: ...
    def type1_changed(self) -> None: ...
    def type2_changed(self) -> None: ...
    def category_changed(self) -> None: ...
    def power_changed(self) -> None: ...
    def accuracy_changed(self) -> None: ...
    def pp_changed(self) -> None: ...
    def save_move(self) -> None: ...
    def get_file_path(self, file_name: str) -> Tuple[Path, Path]: ...
